In [2]:
import numpy as np

A = np.array([[1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 2, 0],
              [0, 0, 0, 1]])

B = np.array([[1, 1, 1, 1],
              [2, 2, 2, 2],
              [3, 3, 3, 3],
              [4, 4, 4, 4]])

np.einsum("ft,mf->mt", A, B)


A[0:4][0]


array([1, 0, 0, 0])

In [6]:
for idx, i in np.ndenumerate(np.arange(10) * 10):
    print(idx[-1], i)


0 0
1 10
2 20
3 30
4 40
5 50
6 60
7 70
8 80
9 90


In [43]:
X = np.array([
    [0, 0, 0, 0, 0],
    [1, 1, 1, 1, 1],
    [2, 2, 2, 2, 2],
    [3, 3, 3, 3, 3],
])

pick = np.array([3, 3, 2, 1, 0])
mask = np.array([True, False, True, False, True])



X[pick[mask], np.arange(X.shape[1])[mask]]


array([3, 2, 0])

In [49]:
x = np.array([x for x in 'abcdefghi']).reshape((3, 3))
mask = np.array([True, False, True])
x[np.array([0, 1, 2])[mask], np.arange(x.shape[1])[mask]]


y = np.zeros_like(x)

y[np.array([0, 1, 2])[mask], np.arange(x.shape[1])[mask]] = x[np.array([0, 1, 2])[mask], np.arange(x.shape[1])[mask]]

y

array([['a', '', ''],
       ['', '', ''],
       ['', '', 'i']], dtype='<U1')

In [56]:
test = [[0, 1], [2, 3], [4, 5]]

np.lib.stride_tricks.sliding_window_view(test, (3), axis=0)


array([[[0, 2, 4],
        [1, 3, 5]]])